# Generated by Django 4.2.20 on 2025-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_admin_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_admission', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=4)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('p_number', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(max_length=12)),
                ('bpl', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=50)),
                ('father_number', models.CharField(max_length=10)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_number', models.CharField(max_length=10)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=12)),
                ('sibling_name1', models.CharField(max_length=50)),
                ('sibling_class1', models.CharField(max_length=50)),
                ('sibling_relation1', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
